---
- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - unzip
    - php5-cli
    - php5-fpm
    - php5-json
    - php5-gd
    - php5-mysql
    - php5-imagick
    - php5-curl

- name: Find PHP ini file
  shell: php -i | grep 'Loaded Configuration File' | sed -e 's/[^\/]*\(\/.*\)$/\1/'
  register: modx_php_ini_file

- name: Configure PHP
  replace: dest={{ modx_php_ini_file.stdout }} regexp='^;date.timezone =$' replace='date.timezone = {{ modx_timezone }}' backup=yes

- name: Create installation directory
  file: path={{ modx_install_dir }} state=directory

- name: Get MODX zipfile
  get_url: url={{modx_download_url}} dest={{ modx_install_dir }}/modx-{{ modx_version }}.zip
  register: got_modx

- name: Unzip MODX
  command: unzip -o modx-{{ modx_version }}.zip
  when: got_modx|changed
  args:
    chdir: "{{ modx_install_dir }}"
    creates: "{{ modx_install_dir }}/modx-{{ modx_version }}"

- name: Configure MODX installation
  template: src=config.xml dest={{ modx_install_dir }}/modx-{{ modx_version }}/setup/config.xml
  when: got_modx|changed

- name: Touch blank config file
  file: path={{ modx_install_dir }}/modx-{{ modx_version }}/core/config/config.inc.php state=touch
  when: got_modx|changed

- name: Install MODX
  command: php ./index.php --installmode=new
  when: got_modx|changed
  args:
    chdir: "{{ modx_install_dir }}/modx-{{ modx_version }}/setup/"


- name: Clean up MODX installation
  file: path={{ modx_install_dir }}/modx-{{ modx_version }}/setup state=absent
